services:
    laravel_franken:
      container_name: laravel_franken
      image: image_laravel_franken
      build: .
      ports:
        - "8000:8000"
      env_file:
        - .env
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 30s
